### ISSUE TITLE
Incompatibility of mentioned Licenses

### ISSUE THREAD

**Issue by band-a-prend** [QcmPlab/SciFortran#10]
The LICENSE.md file refers the "*GNU Lesser General Public License v3.0*" (LGPL-3.0) while README.md refers the "*GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version*" (GPL3+).

It slightly confuses. 

Please update LICENSE.md or README.md with proper license.

**Comment by aamaricci** [comment]
Fixed citing in the README.md the correct license (LGPL-3.0 or later version). Thanks.

**Comment by band-a-prend** [comment]
Thanks. The last 2 paragraphs of README.md still refers GPL instead of LGPL.

Sorry for annoying, it could be meaning for those who will want to package library for linux distributives.

**Comment by aamaricci** [comment]
No problems. Indeed, thanks for pointing this out. 
References to GNU LGPL should now appear everywhere in the README.md.
