### ISSUE TITLE
undefined reference to `integrate_quad_func_'

### ISSUE THREAD

**Issue by WangYun1995** [QcmPlab/SciFortran#4]
Hello,
I met one problem when I tested the functionality of scifor.
The code snippet is shown below.
```
 program test
  Use scifor
  Implicit None
  
  real(8) :: Integral

  Call quad_func(sin2, 0.0d0, pi, Integral)
  
  Write (*,*) Integral

! ------------------------------- !  
Contains
  Function sin2(x)
    Real(8) :: sin2
	Real(8) :: x
	
	sin2 = sin(x)**2
  End Function
end Program test
```

After I input directives ```gfortran test_integrate.f95 -I/home/wangy/opt/scifor/gnu/4.6.31/include -L/home/wangy/opt/scifor/gnu/4.6.31/lib -lscifor /usr/lib64/liblapack.so /usr/lib64/libblas.so ```,
it returned me an error information which is shown below.

```
/tmp/ccbOEfEL.o: In function `MAIN__':
test_integrate.f95:(.text+0x8c): undefined reference to `integrate_quad_func_'
collect2: error: ld returned 1 exit status
```

How to solve this probelm?

**Comment by aamaricci** [comment]
The quad interface is a subroutine so the correct program is:
program test
  Use scifor
  Implicit None
  real(8) :: Integral
  call quad(sin2, 0.0d0, pi, result=integral)
  Write (*,*) Integral
  ! ------------------------------- !  
Contains
  Function sin2(x)
    Real(8) :: sin2
    Real(8) :: x
    sin2 = sin(x)**2
  End Function sin2
end Program test

$ mpif90 $(pkg-config --cflags --libs scifor) test.f90 
$ ./a.out 
   1.5707963097588762  

Cheers,
A

**Comment by WangYun1995** [comment]
Thank you!
When I used the compile command ```(pkg-config --cflags --libs scifor) test.f95```, it returned ```-bash: -I/home/wangy/opt/scifor/gnu/4.6.31/include: No such file or directory``` to me.

However,  when I input ```gfortran test.f95 -I/home/wangy/opt/scifor/gnu/4.6.31/include -L/home/wangy/opt/scifor/gnu/4.6.31/lib -lscifor /usr/lib64/liblapack.so /usr/lib64/libblas.so```, 
it returned me ```./a.out```.

Why did I fail to use ``` $(pkg-config --cflags --libs scifor) test.f95```?

**Comment by aamaricci** [comment]
That’s because you need to load the library into your system. Follow
instructions printed after the
make post-install
step.

This way the library is recognized as part of the os and you can use
pkg-config to retrieve linking information.

Cheers
A


Il giorno mar 1 dic 2020 alle 15:58 WangYun1995 <notifications@github.com>
ha scritto:

**Comment by WangYun1995** [comment]
According to your advice, I follow instructions printed after the make post-install. But there is another issue shown below.
![QQ图片20201202093941](https://user-images.githubusercontent.com/68187127/100817028-561bfe00-3482-11eb-98ed-6d7f513c5e06.png)

Why is there a ```\;```  in ``` /usr/lib64/liblapack.so\;/usr/lib64/libblas.so```?  I think the ```\;``` leads to the gfortran error. How to address it?

**Comment by aamaricci** [comment]
This looks like the pkg-config configuration file for SCIFOR is corrupted. 
pkg-config report informations about linking (and other) directives for any installed library in the system. This is done by reading suitable configuration files specific to each library. Each such file is provided together with the library and placed in specific system directories, where pkg-config can find and read, as stored in the environment variable PKG_CONFIG_PATH. The file have the form <library_name>.pc

Together with SCIFOR we thus provide a scifor.pc file, which is created by Cmake during post-install step. To avoid getting access to system directory we place such file in your home under ~/.pkgconfig.d. This directory is then added to the PKG_CONFIG_PATH by one of the method listed after $make post-install. In this way you can always retrieve linking information no matter where you compile using the $(pkg-config --cflags --libs scifor) string. 

In some cases (depending on the Linux distro) this file scifor.pc comes out corrupted. You need to fix it by removing the \;\;/usr/lib64/libblas.so and replacing it with a space. There should be only one reference to lapack and one to blas. 

Note that this string is generated by a CMake macro that we use to search Lapack/Blas library. 
  
This should solve your problem. 

Cheers,
A

**Comment by WangYun1995** [comment]
So how to removing the ;;/usr/lib64/libblas.so?

**Comment by aamaricci** [comment]
you open the file
~/.pkgconfig.d/scifor.pc
and edit it accordingly.

A

**Comment by WangYun1995** [comment]
Thank you so much!

**Comment by band-a-prend** [comment]
@aamaricci ,
> string is generated by a CMake macro

It seems that issue could be resolved by placing

```
STRING(REPLACE ";" " " LAPACK_LIBRARIES ${LAPACK_LIBRARIES})
```
into cmake/BuildPkgConfigFile.cmake before IF statements. And I need to check if this replacement works as I has described issue in my system.

LAPACK_LIBRARIES returns paths to `/usr/lib64/lapack.so;/usr/lib64/blas.so` by cmake for lapack implementation installed in my case. Additional path from BLAS_LIBRARIES string just add one blas library `/usr/lib64/blas.so` path if available and doesn't cause problem.

But I didn't check if this replacement affects other  cmake files later.

**Comment by aamaricci** [comment]
I see. 
Thanks for pointing this out. I'll try to implement this in a separate branch. Should this works as expected we can integrate it in the stable version.

**Comment by band-a-prend** [comment]
I will update my gentoo package (not ready yet) for scifortran and will make additionally tests with some example that uses blas.

At least for 4.7.4 with example for newton()  (no blas of couse) there was no ld errors with double blas library linked.

**Comment by aamaricci** [comment]
Packaging for Linux distro would be a very welcome upgrade. Please let us know and thanks for trying.

**Comment by band-a-prend** [comment]
> STRING(REPLACE ";" " " LAPACK_LIBRARIES ${LAPACK_LIBRARIES})

It should be (quoted last variable)
`STRING(REPLACE ";" " " LAPACK_LIBRARIES "${LAPACK_LIBRARIES}")` otherwise ";" will be replaced with empty string.

I update my patch with some more common cases (remove duplicates) but need to scifor with lapack related example.
