### ISSUE TITLE
Issues about FFT

### ISSUE THREAD

**Issue by WangYun1995** [QcmPlab/SciFortran#6]
Hello,

I want to analyze the spectrum of a 1D spatial function ```dens(x)``` by computing the Fourier Transform of it.
And I find that there are many interfaces for FFT, such as ```rfft_1d_forward```, ```cfft_1d_forward``` and  ```cfft_1d_backward```. 
What are the differences between them? What are the outputs?
 Could you introduce them to me briefly?
Thank you!

**Comment by aamaricci** [comment]
As for SciPy, these are all interface to FFTPACK main functions. 
We follow closely  the SciPy setup here, take a look at: https://docs.scipy.org/doc/scipy/reference/fft.html
Or directly to FFTPACK documentation. 

forward real and complex FFT are wrapped into fft 
inverse or backward FFT are wrapped in ifft

There are many different cases (1d, 2d, nd, cos, sin, etc..), there are helpers functions like fftshift. 
You should know a bit about discrete FFT to really understand what you need. 

There are in addition even simple discrete FT, not really fast, but do the work in simple cases. 
A

**Comment by WangYun1995** [comment]
Hi,
Does the Scifor provide an interface to ```FFTW```?

**Comment by aamaricci** [comment]
In the current implementation it does not. It should be straightforward to adapt the FFTPACK interface to FFTW library.

**Comment by WangYun1995** [comment]
Ok, thank you for your reply:)

Adriano Amaricci <notifications@github.com> 于2020年12月7日周一 下午4:33写道：
